"""Question -> acceptable doc_ids, used to measure retrieval accuracy (hit@k).

Questions are phrased the way users ask, not copied from the documents.
"""

IN_SCOPE: list[tuple[str, set[str]]] = [
    ("ภาควิชาวิศวกรรมคอมพิวเตอร์เรียนเกี่ยวกับอะไร", {"ce-overview", "program-structure"}),
    ("เป้าหมายของภาควิชาคืออะไร", {"ce-overview"}),
    ("เรียนกี่ปีถึงจะจบ", {"ce-overview"}),
    ("ปรัชญาของมหาวิทยาลัยคืออะไร", {"ce-overview"}),
    ("จบไปแล้วจะมีความสามารถด้านไหนบ้าง", {"ce-overview", "careers"}),
    ("วิสัยทัศน์ของ มทร.ธัญบุรี", {"ce-overview"}),
    ("หลักสูตรมีทั้งหมดกี่หน่วยกิต", {"program-structure", "ce-overview"}),
    ("ชื่อปริญญาภาษาอังกฤษคืออะไร", {"program-structure"}),
    ("หมวดวิชาศึกษาทั่วไปต้องเรียนกี่หน่วยกิต", {"program-structure"}),
    ("PLO ของหลักสูตรมีอะไรบ้าง", {"program-structure"}),
    ("วิชาเลือกเสรีกี่หน่วยกิต", {"program-structure"}),
    ("หลักสูตรนี้มีจุดเด่นอะไร", {"program-structure"}),
    ("จบ ปวช. สมัครเรียนได้ไหม", {"admission"}),
    ("คุณสมบัติของผู้สมัครเข้าเรียน", {"admission", "ce-overview"}),
    ("จบ ปวส. มาเรียนกี่ปี", {"admission"}),
    ("เลือกสาขาตอนปีไหน", {"admission"}),
    ("ม.6 สายวิทย์คณิตเข้าได้ไหม", {"admission"}),
    ("ค่าเทอมเท่าไหร่", {"tuition-fees"}),
    ("ค่าเรียนตลอดหลักสูตรประมาณเท่าไร", {"tuition-fees"}),
    ("ภาคฤดูร้อนต้องจ่ายเท่าไหร่", {"tuition-fees"}),
    ("มีทุนการศึกษาไหม", {"tuition-fees"}),
    ("จบแล้วทำงานอะไรได้บ้าง", {"careers"}),
    ("เป็นนักพัฒนาซอฟต์แวร์ได้ไหม", {"careers"}),
    ("อาชีพวิศวกรระบบเครือข่าย", {"careers"}),
    ("ภาคมีห้องแล็บอะไรบ้าง", {"labs-facilities"}),
    ("มีคอมพิวเตอร์ให้ใช้กี่เครื่อง", {"labs-facilities"}),
    ("จะขอใช้ห้องประชุมต้องทำยังไง", {"labs-facilities"}),
    ("มีห้อง IoT ไหม", {"labs-facilities"}),
    ("ออกสหกิจต้องได้เกรดเฉลี่ยเท่าไหร่", {"coop-internship"}),
    ("ก่อนไปฝึกงานต้องเรียนผ่านวิชาอะไร", {"coop-internship"}),
    ("รหัสวิชาสหกิจศึกษา", {"coop-internship"}),
    ("เบอร์โทรภาควิชา", {"contact", "staff"}),
    ("ภาคอยู่ที่ไหน ที่อยู่อะไร", {"contact"}),
    ("เพจเฟซบุ๊กของภาค", {"contact"}),
    ("ติดต่อภาคได้กี่โมงถึงกี่โมง", {"contact"}),
    ("หัวหน้าภาควิชาคือใคร", {"staff"}),
    ("อาจารย์คนไหนสอน Machine Learning", {"staff"}),
    ("ใครสอนวิชา Database Systems", {"staff"}),
    ("เจ้าหน้าที่ธุรการของภาค", {"staff"}),
    ("แบบฟอร์มถอนรายวิชาหาได้ที่ไหน", {"faq-current-student"}),
    ("ปฏิทินการศึกษาปี 2569", {"faq-current-student"}),
    ("ลงทะเบียนเกินหน่วยกิตต้องทำยังไง", {"faq-current-student"}),
    ("ดาวน์โหลดเล่มหลักสูตรได้ที่ไหน", {"faq-current-student", "program-structure", "ce-overview"}),
    ("ใบยืมอุปกรณ์ของภาค", {"faq-current-student", "labs-facilities"}),
]

# Written after tuning QUERY_SYNONYMS / MIN_COVERAGE and never used to tune them:
# measures how well the retriever generalizes to new phrasings.
HELD_OUT: list[tuple[str, set[str]]] = [
    ("อยากรู้ว่าภาคคอมมีเป้าหมายอะไร", {"ce-overview"}),
    ("พันธกิจของมหาวิทยาลัยมีอะไรบ้าง", {"ce-overview"}),
    ("ปริญญาที่ได้ชื่อย่อว่าอะไร", {"program-structure"}),
    ("กลุ่มวิชาบังคับกี่หน่วยกิต", {"program-structure"}),
    ("วัตถุประสงค์ของหลักสูตร PEO", {"program-structure"}),
    ("เรียนสายอาชีพมาสมัครได้ไหม", {"admission"}),
    ("เทียบโอนจาก ปวส. ได้ไหม", {"admission", "ce-overview"}),
    ("ค่าใช้จ่ายทั้งหมด 4 ปี", {"tuition-fees"}),
    ("ต้องจ่ายค่าลงทะเบียนเทอมละกี่บาท", {"tuition-fees"}),
    ("เรียนจบไปเป็นวิศวกรอะไรได้บ้าง", {"careers"}),
    ("สายงานที่รองรับหลังเรียนจบ", {"careers", "ce-overview"}),
    ("ห้องเรียนรองรับได้กี่คน", {"labs-facilities"}),
    ("มีห้องทำโปรเจกต์ไหม", {"labs-facilities"}),
    ("เงื่อนไขการออกฝึกประสบการณ์วิชาชีพ", {"coop-internship"}),
    ("ฝึกงานต้องผ่านวิชาไมโครคอนโทรลเลอร์ก่อนไหม", {"coop-internship"}),
    ("อีเมลหรือช่องทางติดต่อภาควิชา", {"contact"}),
    ("ภาคตั้งอยู่จังหวัดอะไร", {"contact"}),
    ("รองหัวหน้าภาคฝ่ายวิชาการคือใคร", {"staff"}),
    ("อาจารย์ที่สอน Internet of Things", {"staff"}),
    ("เจ้าหน้าที่ห้องปฏิบัติการมีใครบ้าง", {"staff", "labs-facilities"}),
    ("ขอลาป่วยต้องใช้ฟอร์มอะไร", {"faq-current-student"}),
    ("ตารางปฏิทินการศึกษาดูได้ที่ไหน", {"faq-current-student"}),
    ("ยื่นผลสอบภาษาอังกฤษก่อนจบใช้แบบฟอร์มไหน", {"faq-current-student"}),
    ("ตำราวิชาการสื่อสารข้อมูล", {"faq-current-student", "staff"}),
]

OUT_OF_SCOPE: list[str] = [
    "ราคาทองวันนี้",
    "พรุ่งนี้ฝนจะตกไหม",
    "สูตรต้มยำกุ้ง",
    "ใครชนะฟุตบอลโลก",
    "หุ้นตัวไหนน่าซื้อ",
    "แนะนำร้านกาแฟแถวสยาม",
    "วิธีทำเค้กช็อกโกแลต",
    "ดูดวงความรักเดือนนี้",
    "ตั๋วเครื่องบินไปญี่ปุ่นราคาเท่าไหร่",
    "เขียนกลอนวันแม่ให้หน่อย",
]
