"""Question -> acceptable doc_ids, used to measure retrieval accuracy (hit@k).

When a new document also answers a question correctly, its doc_id is added to
that question's acceptable set (e.g. both co-op documents give the 2.00 GPA rule).

Questions are phrased the way users ask, not copied from the documents.
"""

IN_SCOPE: list[tuple[str, set[str]]] = [
    ("ภาควิชาวิศวกรรมคอมพิวเตอร์เรียนเกี่ยวกับอะไร", {"ce-overview", "program-structure"}),
    ("เป้าหมายของภาควิชาคืออะไร", {"ce-overview"}),
    ("เรียนกี่ปีถึงจะจบ", {"ce-overview"}),
    ("ปรัชญาของมหาวิทยาลัยคืออะไร", {"ce-overview"}),
    ("จบไปแล้วจะมีความสามารถด้านไหนบ้าง", {"ce-overview", "careers"}),
    ("วิสัยทัศน์ของ มทร.ธัญบุรี", {"ce-overview"}),
    ("หลักสูตรมีทั้งหมดกี่หน่วยกิต", {"program-structure", "ce-overview"}),
    ("ชื่อปริญญาภาษาอังกฤษคืออะไร", {"program-structure"}),
    ("หมวดวิชาศึกษาทั่วไปต้องเรียนกี่หน่วยกิต", {"program-structure"}),
    ("PLO ของหลักสูตรมีอะไรบ้าง", {"program-structure"}),
    ("วิชาเลือกเสรีกี่หน่วยกิต", {"program-structure"}),
    ("หลักสูตรนี้มีจุดเด่นอะไร", {"program-structure"}),
    ("จบ ปวช. สมัครเรียนได้ไหม", {"admission"}),
    ("คุณสมบัติของผู้สมัครเข้าเรียน", {"admission", "ce-overview"}),
    ("จบ ปวส. มาเรียนกี่ปี", {"admission"}),
    ("เลือกสาขาตอนปีไหน", {"admission"}),
    ("ม.6 สายวิทย์คณิตเข้าได้ไหม", {"admission"}),
    ("ค่าเทอมเท่าไหร่", {"tuition-fees"}),
    ("ค่าเรียนตลอดหลักสูตรประมาณเท่าไร", {"tuition-fees"}),
    ("ภาคฤดูร้อนต้องจ่ายเท่าไหร่", {"tuition-fees"}),
    ("มีทุนการศึกษาไหม", {"tuition-fees", "scholarships"}),
    ("จบแล้วทำงานอะไรได้บ้าง", {"careers"}),
    ("เป็นนักพัฒนาซอฟต์แวร์ได้ไหม", {"careers"}),
    ("อาชีพวิศวกรระบบเครือข่าย", {"careers"}),
    ("ภาคมีห้องแล็บอะไรบ้าง", {"labs-facilities"}),
    ("มีคอมพิวเตอร์ให้ใช้กี่เครื่อง", {"labs-facilities"}),
    ("จะขอใช้ห้องประชุมต้องทำยังไง", {"labs-facilities"}),
    ("มีห้อง IoT ไหม", {"labs-facilities"}),
    ("ออกสหกิจต้องได้เกรดเฉลี่ยเท่าไหร่", {"coop-internship", "coop-internship-2563"}),
    ("ก่อนไปฝึกงานต้องเรียนผ่านวิชาอะไร", {"coop-internship", "coop-internship-2563"}),
    ("รหัสวิชาสหกิจศึกษา", {"coop-internship", "coop-internship-2563"}),
    ("เบอร์โทรภาควิชา", {"contact", "staff"}),
    ("ภาคอยู่ที่ไหน ที่อยู่อะไร", {"contact"}),
    ("เพจเฟซบุ๊กของภาค", {"contact"}),
    ("ติดต่อภาคได้กี่โมงถึงกี่โมง", {"contact"}),
    ("หัวหน้าภาควิชาคือใคร", {"staff"}),
    ("อาจารย์คนไหนสอน Machine Learning", {"staff"}),
    ("ใครสอนวิชา Database Systems", {"staff"}),
    ("เจ้าหน้าที่ธุรการของภาค", {"staff"}),
    ("แบบฟอร์มถอนรายวิชาหาได้ที่ไหน", {"faq-current-student"}),
    ("ปฏิทินการศึกษาปี 2569", {"faq-current-student"}),
    ("ลงทะเบียนเกินหน่วยกิตต้องทำยังไง", {"faq-current-student"}),
    ("ดาวน์โหลดเล่มหลักสูตรได้ที่ไหน", {"faq-current-student", "program-structure", "ce-overview"}),
    ("ใบยืมอุปกรณ์ของภาค", {"faq-current-student", "labs-facilities"}),
    # Added with coop-internship-2563 / student-projects (knowledge-v2), including ones
    # that still miss rank 1, so the tuning score is not cherry-picked.
    ("หลักสูตร 63 ก่อนไปสหกิจต้องผ่านวิชาอะไร", {"coop-internship-2563"}),
    ("เด็กหลักสูตร 58 ฝึกงานต้องผ่านวิชาอะไรบ้าง", {"coop-internship-2563"}),
    ("ตัวอย่างโปรเจกต์จบของรุ่นพี่", {"student-projects"}),
    ("มีโครงงานเกี่ยวกับ image processing ไหม", {"student-projects", "staff"}),
    # Added with admission-schedule-2570 / scholarships.
    ("TCAS1 รอบ portfolio เปิดรับสมัครเมื่อไหร่", {"admission-schedule-2570"}),
    ("รอบโควตาปี 2570 สมัครได้ถึงวันไหน", {"admission-schedule-2570"}),
    ("มีทุนสำหรับนักศึกษาขาดแคลนไหม", {"scholarships"}),
    ("กู้ กยศ. ติดต่อที่ไหน", {"scholarships"}),
]

# Written after tuning QUERY_SYNONYMS / MIN_COVERAGE and never used to tune them:
# measures how well the retriever generalizes to new phrasings.
HELD_OUT: list[tuple[str, set[str]]] = [
    ("อยากรู้ว่าภาคคอมมีเป้าหมายอะไร", {"ce-overview"}),
    ("พันธกิจของมหาวิทยาลัยมีอะไรบ้าง", {"ce-overview"}),
    ("ปริญญาที่ได้ชื่อย่อว่าอะไร", {"program-structure"}),
    ("กลุ่มวิชาบังคับกี่หน่วยกิต", {"program-structure"}),
    ("วัตถุประสงค์ของหลักสูตร PEO", {"program-structure"}),
    ("เรียนสายอาชีพมาสมัครได้ไหม", {"admission"}),
    ("เทียบโอนจาก ปวส. ได้ไหม", {"admission", "ce-overview"}),
    ("ค่าใช้จ่ายทั้งหมด 4 ปี", {"tuition-fees"}),
    ("ต้องจ่ายค่าลงทะเบียนเทอมละกี่บาท", {"tuition-fees"}),
    ("เรียนจบไปเป็นวิศวกรอะไรได้บ้าง", {"careers"}),
    ("สายงานที่รองรับหลังเรียนจบ", {"careers", "ce-overview"}),
    ("ห้องเรียนรองรับได้กี่คน", {"labs-facilities"}),
    ("มีห้องทำโปรเจกต์ไหม", {"labs-facilities"}),
    ("เงื่อนไขการออกฝึกประสบการณ์วิชาชีพ", {"coop-internship", "coop-internship-2563"}),
    ("ฝึกงานต้องผ่านวิชาไมโครคอนโทรลเลอร์ก่อนไหม", {"coop-internship"}),
    ("อีเมลหรือช่องทางติดต่อภาควิชา", {"contact"}),
    ("ภาคตั้งอยู่จังหวัดอะไร", {"contact"}),
    ("รองหัวหน้าภาคฝ่ายวิชาการคือใคร", {"staff"}),
    ("อาจารย์ที่สอน Internet of Things", {"staff"}),
    ("เจ้าหน้าที่ห้องปฏิบัติการมีใครบ้าง", {"staff", "labs-facilities"}),
    ("ขอลาป่วยต้องใช้ฟอร์มอะไร", {"faq-current-student"}),
    ("ตารางปฏิทินการศึกษาดูได้ที่ไหน", {"faq-current-student"}),
    ("ยื่นผลสอบภาษาอังกฤษก่อนจบใช้แบบฟอร์มไหน", {"faq-current-student"}),
    ("ตำราวิชาการสื่อสารข้อมูล", {"faq-current-student", "staff"}),
]

# Written after the vector + keyword fusion weights were chosen (HELD_OUT was
# looked at while choosing them), measured once: the unbiased check.
HELD_OUT_2: list[tuple[str, set[str]]] = [
    ("ภาควิชานี้อยากผลิตวิศวกรแบบไหน", {"ce-overview", "program-structure"}),
    ("เรียนแบบเทียบโอนจบได้ภายในกี่ปี", {"ce-overview", "admission"}),
    ("ชื่อหลักสูตรภาษาอังกฤษเขียนว่าอะไร", {"program-structure"}),
    ("กลุ่มวิชาพื้นฐานต้องเก็บกี่หน่วยกิต", {"program-structure"}),
    ("ปวช. สาขาไหนสมัครเข้าได้บ้าง", {"admission"}),
    ("เรียนนอกเวลาได้ไหม", {"admission"}),
    ("เรียนสี่ปีจ่ายค่าเทอมรวมเท่าไหร่", {"tuition-fees"}),
    ("หลักสูตรใหม่ค่าเทอมเทอมละเท่าไร", {"tuition-fees"}),
    ("จบไปทำงานสายซอฟต์แวร์ได้ไหม", {"careers"}),
    ("เรียนจบแล้วเป็นอาจารย์หรือนักวิจัยได้ไหม", {"careers"}),
    ("ห้องเน็ตเวิร์กมีไหม", {"labs-facilities"}),
    ("ขอยืมห้องประชุมทำงานกลุ่ม", {"labs-facilities"}),
    ("ฝึกงานต้องมีจีพีเอขั้นต่ำเท่าไหร่", {"coop-internship", "coop-internship-2563"}),
    ("วิชาฐานข้อมูลต้องผ่านก่อนไปสหกิจไหม", {"coop-internship", "coop-internship-2563"}),
    ("โทรหาภาควิชาเบอร์อะไร", {"contact", "staff"}),
    ("รหัสไปรษณีย์ของภาคคือเท่าไหร่", {"contact"}),
    ("ใครสอนวิชา Operating Systems", {"staff"}),
    ("หัวหน้าธุรการภาควิชาชื่ออะไร", {"staff"}),
    ("อยากถอนวิชาแบบได้ W ใช้ฟอร์มไหน", {"faq-current-student"}),
    ("ลงทะเบียนเรียนข้ามมหาวิทยาลัยต้องยื่นอะไร", {"faq-current-student"}),
]

OUT_OF_SCOPE_2: list[str] = [
    "อากาศที่เชียงใหม่ตอนนี้",
    "สอนทำผัดไทยหน่อย",
    "ผลบอลเมื่อคืน",
    "แนะนำหนังน่าดูปีนี้",
    "วิธีลดน้ำหนักให้ได้ผล",
]

OUT_OF_SCOPE: list[str] = [
    "ราคาทองวันนี้",
    "พรุ่งนี้ฝนจะตกไหม",
    "สูตรต้มยำกุ้ง",
    "ใครชนะฟุตบอลโลก",
    "หุ้นตัวไหนน่าซื้อ",
    "แนะนำร้านกาแฟแถวสยาม",
    "วิธีทำเค้กช็อกโกแลต",
    "ดูดวงความรักเดือนนี้",
    "ตั๋วเครื่องบินไปญี่ปุ่นราคาเท่าไหร่",
    "เขียนกลอนวันแม่ให้หน่อย",
]

# Used while choosing the reranker threshold and the scope rule (so: tuning data).
OUT_OF_SCOPE_NEAR: list[str] = [
    "ภาควิชาวิศวกรรมไฟฟ้าเรียนอะไร",
    "คณะบริหารธุรกิจค่าเทอมเท่าไหร่",
    "จุฬาเปิดรับสมัครเมื่อไหร่",
    "วิธีเขียนเรซูเม่สมัครงาน",
    "สอนเขียน python เบื้องต้น",
    "แนะนำโน้ตบุ๊กสำหรับเขียนโปรแกรม",
    "ช่วยทำการบ้านแคลคูลัสให้หน่อย",
    "ประวัติศาสตร์สมัยอยุธยา",
    "เล่นเกมอะไรดี",
    "ข่าวการเมืองวันนี้",
    "หอพักใกล้มหาลัยราคาถูก",
    "ร้านข้าวมันไก่อร่อยแถวรังสิต",
    "โควิดรักษายังไง",
    "แปลภาษาอังกฤษประโยคนี้ให้หน่อย",
    "สมัครบัตรเครดิตยังไง",
    "ภาควิชาเคมีอยู่ตึกไหน",
    "มหาวิทยาลัยเกษตรมีคณะอะไรบ้าง",
    "วันหยุดราชการเดือนหน้า",
    "โปรแกรมแต่งรูปฟรีตัวไหนดี",
    "ซื้อหุ้นยังไง",
]

# Written after the whole hybrid pipeline (BM25 + vector + reranker + scope rule)
# was fixed, and measured once. These are the numbers to quote.
HELD_OUT_3: list[tuple[str, set[str]]] = [
    ("ภาคคอมเน้นสอนด้านไหน", {"ce-overview", "program-structure"}),
    ("หลักสูตรใหม่ปรับปรุงปีไหน", {"program-structure", "faq-current-student"}),
    ("หมวดวิชาเฉพาะมีกี่หน่วยกิต", {"program-structure"}),
    ("PLO ข้อที่เกี่ยวกับการทำงานเป็นทีม", {"program-structure"}),
    ("ปี 3 เทอม 1 เรียนวิชาอะไรเด่น ๆ", {"study-plan-overview"}),
    ("ปี 4 ต้องไปสหกิจกี่หน่วยกิต", {"study-plan-overview", "coop-internship"}),
    ("จบสายช่างอิเล็กทรอนิกส์มาเรียนได้ไหม", {"admission"}),
    ("กรรมการหลักสูตรพิจารณาคุณสมบัติกรณีพิเศษไหม", {"admission"}),
    ("ภาคฤดูร้อนต้องจ่ายค่าเรียนเท่าไหร่", {"tuition-fees"}),
    ("เรียนเทียบโอนสามปีค่าใช้จ่ายรวมเท่าไหร่", {"tuition-fees"}),
    ("อยากเป็น network engineer เรียนที่นี่ได้ไหม", {"careers"}),
    ("จบแล้วเปิดธุรกิจของตัวเองได้ไหม", {"careers"}),
    ("ห้องเรียนมีโปรเจกเตอร์ไหม", {"labs-facilities"}),
    ("มีเครื่องมือช่างให้เบิกไหม", {"labs-facilities"}),
    ("ก่อนไปฝึกงานต้องผ่านวิชา OOP ไหม", {"coop-internship", "coop-internship-2563"}),
    ("ข้อกำหนดสหกิจเริ่มใช้เทอมไหน", {"coop-internship", "coop-internship-2563"}),
    ("ภาคเปิดทำการวันไหนบ้าง", {"contact"}),
    ("ส่งข้อความหาภาควิชาทางไหนได้บ้าง", {"contact"}),
    ("ใครเป็นรองหัวหน้าภาคฝ่ายพัฒนานักศึกษา", {"staff"}),
    ("อาจารย์ที่สอน Embedded Systems", {"staff"}),
    ("นักวิชาการศึกษาด้านห้องปฏิบัติการชื่ออะไร", {"staff"}),
    ("ขอเอกสารการศึกษาใช้แบบฟอร์มอะไร", {"faq-current-student"}),
    ("อยากลงทะเบียนเรียนแทนวิชาที่ติด F", {"faq-current-student"}),
    ("ปฏิทินการศึกษาปี 2568 ดูได้ที่ไหน", {"faq-current-student"}),
    ("อยากแก้ค่า I ต้องยื่นอะไร", {"faq-current-student"}),
]

OUT_OF_SCOPE_3: list[str] = [
    "ภาควิชาวิศวกรรมโยธาเรียนกี่ปี",
    "คณะครุศาสตร์รับสมัครเมื่อไหร่",
    "ลาดกระบังวิศวะคอมค่าเทอมเท่าไหร่",
    "วิธีตั้งค่า router ที่บ้าน",
    "เขียนเว็บด้วย React ยังไง",
    "ซื้อคอมประกอบงบสองหมื่น",
    "ข้อสอบ TOEIC ยากไหม",
    "แนะนำที่เที่ยวทะเลใกล้กรุงเทพ",
    "ทำไมท้องฟ้าเป็นสีฟ้า",
    "ช่วยคิดชื่อร้านกาแฟหน่อย",
    "ราคาน้ำมันพรุ่งนี้",
    "ปวดหัวกินยาอะไรดี",
    "ดูบอลพรีเมียร์ลีกที่ไหน",
    "สอนทำข้าวผัดกะเพรา",
    "เงินเดือนข้าราชการเท่าไหร่",
    "iPhone รุ่นใหม่ออกเมื่อไหร่",
    "วิธีแก้เน็ตช้า",
    "คะแนนสอบ TCAS คณะแพทย์",
    "ออกกำลังกายลดพุง",
    "หนังสือนิยายแนะนำ",
]

# Written after MIN_RELEVANCE = 0.005 and RERANK_CANDIDATES = 6 were fixed
# (HELD_OUT_3 had been looked at while choosing them), measured once.
HELD_OUT_4: list[tuple[str, set[str]]] = [
    ("ภาควิชาคอมพิวเตอร์มีเป้าหมายด้านงานวิจัยไหม", {"ce-overview"}),
    ("ปณิธานของมหาวิทยาลัยคืออะไร", {"ce-overview"}),
    ("อัตลักษณ์ของ มทร.ธัญบุรี", {"ce-overview"}),
    ("เรียนจบต่อปริญญาโทได้ไหม", {"ce-overview"}),
    ("หลักสูตรนี้ได้วุฒิอะไร", {"program-structure", "ce-overview"}),
    ("กลุ่มวิชาภาษาเพื่อการสื่อสารกี่หน่วยกิต", {"program-structure"}),
    ("ต้องเรียนวิชาเลือกกี่หน่วยกิต", {"program-structure"}),
    ("หลักสูตรเก่าปี 2558 ยังดาวน์โหลดได้ไหม", {"program-structure", "faq-current-student"}),
    ("เป้าหมายของหลักสูตรเรื่องเซมิคอนดักเตอร์", {"program-structure", "careers"}),
    ("ปี 1 เทอม 2 เรียนอะไรบ้างโดยรวม", {"study-plan-overview"}),
    ("ปี 2 ต้องเรียนกี่หน่วยกิต", {"study-plan-overview"}),
    ("ปีสุดท้ายทำโครงงานไหม", {"study-plan-overview"}),
    ("จบ ปวส. เทคนิคคอมพิวเตอร์สมัครได้ไหม", {"admission"}),
    ("เข้าปี 1 แล้วได้เลือกสาขาเลยไหม", {"admission"}),
    ("เรียนภาคพิเศษได้ไหม", {"admission"}),
    ("สมัครเรียนต้องจบสายไหนบ้าง", {"admission", "ce-overview"}),
    ("ค่าเทอมหลักสูตรใหม่เท่าไหร่", {"tuition-fees"}),
    ("ค่าใช้จ่ายสี่ปีรวมประมาณเท่าไร", {"tuition-fees"}),
    ("มีทุนให้ไหม", {"tuition-fees", "scholarships"}),
    ("อยากเป็นนักพัฒนาซอฟต์แวร์เรียนที่นี่ได้ไหม", {"careers"}),
    ("จบไปเป็นวิศวกรฮาร์ดแวร์ได้ไหม", {"careers"}),
    ("มีห้องปฏิบัติการดิจิทัลไหม", {"labs-facilities"}),
    ("ห้องทำโครงงานมีอุปกรณ์อะไรบ้าง", {"labs-facilities"}),
    ("ห้องเรียนมีแอร์ไหม", {"labs-facilities"}),
    ("ยืมอุปกรณ์ของภาคใช้ฟอร์มไหน", {"faq-current-student", "labs-facilities"}),
    ("ก่อนออกสหกิจต้องผ่านไมโครคอนโทรลเลอร์ไหม", {"coop-internship"}),
    ("รหัสวิชาฝึกงานคืออะไร", {"coop-internship", "coop-internship-2563"}),
    ("ฝึกงานนานกี่เดือน", {"coop-internship", "ce-overview"}),
    ("ใครเป็นคนลงนามข้อกำหนดสหกิจ", {"coop-internship", "coop-internship-2563"}),
    ("ภาควิชาอยู่ถนนอะไร", {"contact"}),
    ("เบอร์ติดต่อภาคคอม", {"contact", "staff"}),
    ("ภาคมีเฟซบุ๊กไหม", {"contact"}),
    ("หัวหน้าภาคคอมคือใคร", {"staff"}),
    ("ใครสอนวิชา Computer Security", {"staff"}),
    ("อาจารย์ที่สอน Data Mining", {"staff"}),
    ("รองหัวหน้าภาคฝ่ายวิชาการ", {"staff"}),
    ("ขอลากิจต้องใช้ฟอร์มอะไร", {"faq-current-student"}),
    ("ขอสอบย้อนหลังต้องใช้แบบฟอร์มไหน", {"faq-current-student"}),
    ("แบบฟอร์มขอสำเร็จการศึกษา", {"faq-current-student"}),
    ("ลงทะเบียนต่ำกว่าเกณฑ์ต้องยื่นอะไร", {"faq-current-student"}),
]

OUT_OF_SCOPE_4: list[str] = [
    "ภาควิชาวิศวกรรมเครื่องกลเรียนอะไร",
    "มหาวิทยาลัยมหิดลรับสมัครเมื่อไหร่",
    "สาขาอุตสาหการจบไปทำงานอะไร",
    "สอนเขียน SQL ให้หน่อย",
    "อธิบายทฤษฎีสัมพัทธภาพ",
    "จองโรงแรมที่หัวหิน",
    "เช็กเลขพัสดุไปรษณีย์ไทย",
    "วิธีปลูกกุหลาบ",
    "ช่วยเขียนจดหมายลาออกจากงาน",
    "ราคาบิตคอยน์วันนี้",
    "แนะนำเพลงฟังสบาย ๆ",
    "ดูดวงราศีเมษ",
    "วิธีทำไข่เจียวให้ฟู",
    "ต่อภาษีรถยนต์ออนไลน์",
    "เครื่องบินไปเชียงใหม่กี่ชั่วโมง",
    "คำนวณ BMI ให้หน่อย",
    "ประเทศไทยมีกี่จังหวัด",
    "เลี้ยงแมวต้องเตรียมอะไร",
    "ซีรีส์เกาหลีเรื่องไหนสนุก",
    "สมัครงานราชการต้องสอบอะไร",
]

# Written with admission-schedule-2570 / scholarships / coop-internship-2563 /
# student-projects added and before any measurement on 15 documents.
HELD_OUT_5: list[tuple[str, set[str]]] = [
    ("TCAS รอบสาม admission สมัครวันไหน", {"admission-schedule-2570"}),
    ("รอบสอบตรงของมหาวิทยาลัยปี 2570 เปิดเมื่อไหร่", {"admission-schedule-2570"}),
    ("โครงการ MOU รับสมัครช่วงไหน", {"admission-schedule-2570"}),
    ("ดูรายละเอียดการสมัครเรียนได้ที่เว็บไหน", {"admission-schedule-2570"}),
    ("ทุนวิพงษ์ให้ปีละเท่าไหร่", {"scholarships"}),
    ("ขอทุนต้องได้เกรดเท่าไหร่", {"scholarships"}),
    ("ได้ทุนแล้วมีงานทำไหม", {"scholarships"}),
    ("ติดต่องานทุนการศึกษาของมหาวิทยาลัยเบอร์อะไร", {"scholarships"}),
    ("หลักสูตรปี 58 ต้องผ่านวิชาอะไรก่อนสหกิจ", {"coop-internship-2563"}),
    ("หลักสูตร 63 ฝึกงานต้องผ่านวิชา IoT ก่อนไหม", {"coop-internship-2563"}),
    ("รุ่นพี่เคยทำโปรเจกต์แอปมือถืออะไรบ้าง", {"student-projects"}),
    ("มีโครงงานระบบยืมคืนอุปกรณ์ไหม", {"student-projects"}),
    ("โปรเจกต์จบแยกพัสดุทำยังไง", {"student-projects"}),
    ("ค่าเทอมภาคฤดูร้อนเท่าไหร่", {"tuition-fees"}),
    ("หัวหน้าภาควิชาชื่ออะไร", {"staff"}),
]

OUT_OF_SCOPE_5: list[str] = [
    "ทุนเรียนต่อต่างประเทศของรัฐบาล",
    "สมัครสอบ ก.พ. ยังไง",
    "โปรเจกต์ทำระบบร้านค้าออนไลน์ช่วยเขียนโค้ดให้หน่อย",
    "TCAS คณะแพทย์จุฬาใช้คะแนนอะไร",
    "ขอยืมเงินด่วน",
]
